services:
  # A Docker web service
  - type: web
    name: alist
    env: docker
    repo: https://vip-yzlab@bitbucket.org/vip-yzlab/files-yzlab.git # optional
    region: oregon # optional (defaults to oregon)
    plan: free # optional (defaults to starter)
    healthCheckPath: /
    envVars:
      - key: PORT
        value: 5244
      - key: DB_TYPE
        value: postgres
        sync: false
      - key: DB_HOST
        value: db.bit.io
        sync: false
      - key: DB_PORT
        value: 5432
        sync: false
      - key: DB_USER
        value: yzon
        sync: false
      - key: DB_PASS
        # value: db_password
        sync: false
      - key: DB_NAME
        value: yzon/yzon
        sync: false
      - key: DB_TABLE_PREFIX
        value: alist_
        sync: false
      - key: ASSETS
        # value: https://npm.elemecdn.com/alist-web@$version/dist
        sync: false
      - key: CACHE_EXPIRATION
        # value: 60
        sync: false
      - key: CLEANUP_INTERVAL
        # value: 120
        sync: false
      