services:
  # A Docker web service
  - type: web
    name: files
    env: docker
    repo: 
    region: oregon
    plan: free
    healthCheckPath: /
    envVars:
      - key: PORT
        value: 5244
      - key: DB_TYPE
        value: postgres
        sync: true
      - key: DB_HOST
        value: db.bit.io
        sync: true
      - key: DB_PORT
        value: 5432
        sync: true
      - key: DB_USER
        value: yzon
        sync: true
      - key: DB_NAME
        value: yzon/yzon
        sync: true
      - key: DB_TABLE_PREFIX
        value: alist_
        sync: true
