services:
  # A Docker web service
  - type: web
    name: alist
    env: docker
    repo: 
    region: oregon
    plan: free
    healthCheckPath: /
    envVars:
      - key: PORT
        value: 5244
      - key: DB_TYPE
        value: postgres
        sync: false
      - key: DB_HOST
        value: db.bit.io
        sync: false
      - key: DB_PORT
        value: 5432
        sync: false
      - key: DB_USER
        value: yzon
        sync: false
      - key: DB_PASS
        # value: db_password
        sync: false
      - key: DB_NAME
        value: yzon/yzon
        sync: false
      - key: DB_TABLE_PREFIX
        value: alist_
        sync: false
      - key: ASSETS
        value: https://npm.elemecdn.com/alist-web@$version/dist
        sync: false
